### PR TITLE
Fix permission error

### PR DESCRIPTION
**Pull request by c0dr**
Installing uwsgi with sudo leads to issues when provisioning again without sudo.

### CODE REVIEW

**Comment by pkatseas** [comment]
:+1:

**Comment by sujaymansingh** [comment]
LGTM!

**Comment by johnspicer** [comment]
LGTMT!

**Comment by pkatseas** [comment]
Btw, it just occurred to me that if we upgrade this role in any playbooks, we'll have to manually fix permission errors with existing uwsgi sudo installations. We should do this in any case, as sudo installations are sort of evil, just thought I'd comment so people are aware

**Pull request merged**
